custom:
  config:
    org: jbkrsls
    frameworkVersion: '2'
    stage: prod

#-------------

provider:
  name: aws
  runtime: nodejs14.x
  profile: jbkr-programmatic-access
  lambdaHashingVersion: '20201221'
mongoDbHost: ${ssm:mongodb-host}
mongoDbPass: ${ssm:mongodb-pass}
mongoDbUser: ${ssm:mongodb-user}
mongoDbDbName: ${ssm:mongodb-db-name}
twitterConsumerKey: ${ssm:twitter-consumer-key}
twitterConsumerSecret: ${ssm:twitter-consumer-secret}
twitterAccessToken: ${ssm:twitter-access-token}
twitterTokenSecret: ${ssm:twitter-token-secret}
twitterBearerToken: ${ssm:twitter-bearer-token}
simpleAuthKey: ${ssm:simple-auth-key}
endpoints:
  content:
    client:
      starter:                           content/client/starter
      profile:                           content/client/profile
      liblab:                            content/client/liblab
      contact:                           content/client/contact
      meta:                              content/client/meta
      fourohfour:                        content/client/fourohfour
